//1.4 Introduction To Data Types

//Strings
let as='a';
let bs="hello"
let cs="This is a string"//any thing inside '' or "" are considered  string inn JS

console.log(as,bs,cs)
//Boolean
let ab=true
let bb=false
console.log(ab,bb)
//Undefined
let name;
console.log(name)

//NUll
let nothing = null;
console.log(nothing);


//Checking Data Types

console.log(typeof(as),typeof(as),typeof(ab),typeof(bb),typeof(name),typeof(nothing))
//from above we concluded that strings are type of string
//bollean are boolean
//undefined are undefined
// whereas null re object

