//DAY2 course STARTED [+] DATE:- 12/17/22 :- 2:55

//2.1 PRIMITIVE DATA TYPES

/* list of primitive Datat types

Primitive data types in JavaScript include:

Numbers - Integers, floats
Strings - Any data under single quote, double quote or backtick quote
Booleans - true or false value
Null - empty value or no value
Undefined - a declared variable without a value
Symbol - A unique value that can be generated by Symbol constructor


*/

let num = 123
let stri = "hello"
let state = true //false
let nothing = null
let udef // Undefined
let sym //symbol 

let n1 = 3
let n2 = 3

console.log(n1 == n2)      // true

let JS = 'JavaScript'
let PY = 'Python'

console.log(JS == PY)  //false 

let lOn = true
let lOff = false

console.log(lOn != lOff) // false



//2.2 Non-Primitive Data Types
/*
Array , Dictonary and simliraly other which are muatbles



*/



// Inserting variable inside string literals
console.log(`Hello world ${JS}`); // `` acts as formator allowing ${} for inserting data insede string


console.log('Hello world ${JS}');//where as '' makes everything insed it string not matter what

//2.3

let sring = " testingString            "
console.log(sring);
console.log(sring.toUpperCase());
console.log(sring.toLowerCase());
console.log(sring.substr(2,5)); //sting , 2 positiona to start from 5 number of 
								//characters to extract
console.log(sring.substring(2,5));//stin  ,2 positiona to start from; 5 positon to end
console.log(sring.split('S'));
console.log(sring.trim('')); //strips out unnecessary spaces from front and back
console.log(sring.includes('t'))//check for presence  of 't' in sring => true
console.log(sring.replace('t','D')) // replaces first apperance of 't' with 'D'
console.log(sring.charAt(1)); //=>sring[1] [=] t
console.log(sring.charCodeAt(1))//returns charcter code of t =>116
console.log(sring.indexOf('t'));//returns indes of first apperance of 't'
console.log(sring.lastIndexOf('t'));//returns indes of last apperance of 't'
console.log(sring.concat('tell'));//concanitiate tell with sring
console.log(sring.search(/s/gi));
console.log(sring.match(/s/g));


//2.4 Type Casting converting one data type to another
let number =10
let numSting = parseInt(number)
let snm = '10'
let Int = Number(snm)
//or
let int = +Int
console.log(number,numSting,snm,Int,int)